name: Hello World!

on:
    push:
        branches:
            - master

jobs:
    hello_world_job:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello World!"
    Now it is:
        runs-on: ubuntu-latest
        steps:
            - name: Run Date
              run: date
    Directory Content:
        runs-on: ubuntu-latest
        steps:
            - name: Run ls
              run: ls
